web:
  image: nginx:1.10
  ports:
    - "8080:80"
  volumes:
    - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./src/public:/var/www/html
  links:
    - php-fpm

php-fpm:
  build: images/php-fpm
  volumes:
    - ./src/public:/var/www/html
    - ./data/uploads:/var/www/html/uploads
  links:
    - db
    - memcached

db:
  image: mysql:5.7
  volumes:
   - ./data/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: kwf
    MYSQL_DATABASE: kwf
    MYSQL_USER: kwf
    MYSQL_PASSWORD: kwf

memcached:
  image: memcached:1.4

maintenance-jobs:
  build: images/maintenance-jobs
  volumes:
    - ./src/public:/var/www/html
    - ./data/uploads:/var/www/html/uploads
  links:
    - db
    - memcached

php-cli:
  build: images/php-cli
  volumes:
    - ./src/public:/var/www/html
    - ./data/uploads:/var/www/html/uploads
  links:
    - db
    - memcached

build:
  build: images/build
  volumes:
    - ./src/public:/var/www/html
